# Generated by Django 3.2.5 on 2021-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image2',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image3',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image4',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
