# Generated by Django 3.2.5 on 2021-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20210724_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image3',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image4',
            field=models.ImageField(upload_to='banners'),
        ),
    ]
