# Generated by Django 3.2.5 on 2021-07-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20210724_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image4',
        ),
    ]
